### ISSUE TITLE
Register NEOK as an IBC coin and get it listed in a dex

### ISSUE THREAD

**Issue by vrde** [NeokingdomDAO/contracts#38]
- [x] Draft proposal and submit it to the EVMOS Commonwealth forum https://commonwealth.im/evmos/discussion/11132-proposal-to-register-neok-token-an-ibc-token
- [x] Submit the proposal and hope it gets accepted https://app.evmos.org/governance?id=144
- [x] Update cosmostation registry for the ERC-20 token https://github.com/cosmostation/chainlist/pull/538
- [x] Update cosmostation registry for the IBC coin https://github.com/cosmostation/chainlist/pull/541
- [x] https://github.com/NeokingdomDAO/dapp/issues/102
- [x] https://github.com/cosmostation/chainlist/pull/599
- [x] https://github.com/cosmostation/chainlist/pull/600
- [x] Ask Cosmostation why our coin doesn't show up https://github.com/cosmostation/cosmostation-chrome-extension/issues/182
- [x] Add NEOK to the EVMOS Token Registry https://github.com/evmos/chain-token-registry/pull/52
- [ ] Figure out how to NEOK to keplr chainlist https://github.com/chainapsis/keplr-chain-registry/issues/136
- [ ] Ask Keplr why our coin doesn't show up https://github.com/chainapsis/keplr-wallet/issues/724
- [x] https://github.com/NeokingdomDAO/dapp/issues/108
- [x] https://github.com/cosmostation/chainlist/pull/766
- [x] https://github.com/cosmostation/chainlist/pull/785
- [x] https://github.com/cosmos/chain-registry/pull/2785
- [x] https://github.com/cosmos/chain-registry/pull/2787
- [x] https://github.com/cosmostation/chainlist/pull/880

Related issues:
- https://github.com/chainapsis/keplr-wallet/issues/735
- https://github.com/evmos/apps/issues/247

Other docs:

- https://academy.evmos.org/articles/advanced/automated-coin-conversion/
- https://ibc.cosmos.network/main/architecture/adr-001-coin-source-tracing.html
- https://github.com/scrtlabs/secret.js/blob/dacb6b491b6b23019ce53deb0664f5bd559c6b9e/test/ibc.test.ts#L254
- https://github.com/scrtlabs/wrap.scrt.network/blob/9fb58842e4ffe57d010e19ab6d497e12e3c2046d/src/Deposit.tsx#L430-L541

**Comment by vrde** [comment]
https://commonwealth.im/evmos/discussion/11132-proposal-to-register-neok-token-an-ibc-token

**Comment by GAtom22** [comment]
Hey @vrde feel free to open a PR on the [Evmos academy repo](https://github.com/evmos/academy) if you want to share your experience about this. We could add a new article or [improve the existing one](https://academy.evmos.org/articles/advanced/erc20-registration). Would be very useful for other developers

**Comment by vrde** [comment]
> Hey @vrde feel free to open a PR on the [Evmos academy repo](https://github.com/evmos/academy) if you want to share your experience about this. We could add a new article or [improve the existing one](https://academy.evmos.org/articles/advanced/erc20-registration). Would be very useful for other developers

Sure thing, I'll work on it after we close the loop with Keplr or Cosmostation :)

**Comment by vrde** [comment]
@GAtom22 to keep you posted, we will work on the article once we have our token in a dex.

**Comment by sirnicolaz** [comment]
The integration of NEOK inside keplr mostly depend on their support for the EVMOS ERC20 tokens. We will close this issue and follow up with the EVMOS team.
